// Generated by tools/faust-build.ts from cavern.dsp. Do not edit.
import type { FaustMeta } from '../FaustNode';
import url from './cavern.wasm?url';

export const cavernUrl = url;

export const cavernMeta = {
  "name": "cavern",
  "inputs": 0,
  "outputs": 1,
  "size": 328516,
  "params": {
    "draught": {
      "at": 188,
      "init": 0.4,
      "min": 0,
      "max": 1,
      "step": 0.001
    },
    "drift": {
      "at": 160,
      "init": 0.5,
      "min": 0,
      "max": 1,
      "step": 0.001
    },
    "floor": {
      "at": 328456,
      "init": 0.6,
      "min": 0,
      "max": 1,
      "step": 0.001
    },
    "gain": {
      "at": 12,
      "init": 0.4,
      "min": 0,
      "max": 1,
      "step": 0.001
    },
    "hard": {
      "at": 40,
      "init": 0.7,
      "min": 0,
      "max": 1,
      "step": 0.001
    },
    "size": {
      "at": 52,
      "init": 45,
      "min": 18,
      "max": 400,
      "step": 0.1
    }
  }
} as const satisfies FaustMeta;

export type CavernParam = keyof typeof cavernMeta.params;
