// Generated by tools/faust-build.ts from friction.dsp. Do not edit.
import type { FaustMeta } from '../FaustNode';
import url from './friction.wasm?url';

export const frictionUrl = url;

export const frictionMeta = {
  "name": "friction",
  "inputs": 0,
  "outputs": 1,
  "size": 216,
  "params": {
    "bright": {
      "at": 32,
      "init": 0.5,
      "min": 0,
      "max": 1,
      "step": 0.001
    },
    "decay": {
      "at": 104,
      "init": 0.5,
      "min": 0.02,
      "max": 3,
      "step": 0.001
    },
    "force": {
      "at": 48,
      "init": 0.5,
      "min": 0,
      "max": 1,
      "step": 0.001
    },
    "gain": {
      "at": 204,
      "init": 0.5,
      "min": 0,
      "max": 1,
      "step": 0.001
    },
    "pitch": {
      "at": 16,
      "init": 180,
      "min": 30,
      "max": 1400,
      "step": 0.1
    },
    "roughness": {
      "at": 72,
      "init": 0.4,
      "min": 0,
      "max": 1,
      "step": 0.001
    },
    "speed": {
      "at": 60,
      "init": 0.3,
      "min": 0,
      "max": 1,
      "step": 0.001
    }
  }
} as const satisfies FaustMeta;

export type FrictionParam = keyof typeof frictionMeta.params;
