// Generated by tools/faust-build.ts from plant.dsp. Do not edit.
import type { FaustMeta } from '../FaustNode';
import url from './plant.wasm?url';

export const plantUrl = url;

export const plantMeta = {
  "name": "plant",
  "inputs": 0,
  "outputs": 1,
  "size": 311720,
  "params": {
    "clank": {
      "at": 262472,
      "init": 0.4,
      "min": 0,
      "max": 1,
      "step": 0.001
    },
    "gain": {
      "at": 262156,
      "init": 0.4,
      "min": 0,
      "max": 1,
      "step": 0.001
    },
    "load": {
      "at": 262240,
      "init": 0.5,
      "min": 0,
      "max": 1,
      "step": 0.001
    },
    "metal": {
      "at": 262192,
      "init": 0.6,
      "min": 0,
      "max": 1,
      "step": 0.001
    },
    "rpm": {
      "at": 262260,
      "init": 220,
      "min": 10,
      "max": 3000,
      "step": 1
    },
    "size": {
      "at": 262180,
      "init": 90,
      "min": 30,
      "max": 600,
      "step": 0.1
    },
    "wear": {
      "at": 262228,
      "init": 0.4,
      "min": 0,
      "max": 1,
      "step": 0.001
    }
  }
} as const satisfies FaustMeta;

export type PlantParam = keyof typeof plantMeta.params;
