// Generated by tools/faust-build.ts from reverb.dsp. Do not edit.
import type { FaustMeta } from '../FaustNode';
import url from './reverb.wasm?url';

export const reverbUrl = url;

export const reverbMeta = {
  "name": "reverb",
  "inputs": 1,
  "outputs": 2,
  "size": 1982988,
  "params": {
    "crossover": 36,
    "damping": 16,
    "decayLow": 24,
    "decayMid": 28,
    "preDelay": 327756
  }
} as const satisfies FaustMeta;

export type ReverbParam = keyof typeof reverbMeta.params;
