// Generated by tools/faust-build.ts from waveguide.dsp. Do not edit.
import type { FaustMeta } from '../FaustNode';
import url from './waveguide.wasm?url';

export const waveguideUrl = url;

export const waveguideMeta = {
  "name": "waveguide",
  "inputs": 1,
  "outputs": 1,
  "size": 32892,
  "params": {
    "bright": {
      "at": 20,
      "init": 0.5,
      "min": 0,
      "max": 1,
      "step": 0.001
    },
    "closed": {
      "at": 0,
      "init": 0,
      "min": 0,
      "max": 1,
      "step": 0.01
    },
    "decay": {
      "at": 72,
      "init": 2,
      "min": 0.05,
      "max": 20,
      "step": 0.01
    },
    "gain": {
      "at": 32880,
      "init": 0.5,
      "min": 0,
      "max": 1,
      "step": 0.001
    },
    "pitch": {
      "at": 40,
      "init": 440,
      "min": 40,
      "max": 4000,
      "step": 0.1
    },
    "place": {
      "at": 32852,
      "init": 0.22,
      "min": 0.02,
      "max": 0.5,
      "step": 0.001
    }
  }
} as const satisfies FaustMeta;

export type WaveguideParam = keyof typeof waveguideMeta.params;
