/**
 * Compiles every `.dsp` in `src/audio/faust/` to wasm.
 *
 * `npm run build:faust`
 *
 * **The output is committed.** `npm run build` must work on a machine that has
 * never heard of Faust, and Pages must deploy exactly what was tested, so the
 * compiler runs here and its artifacts go into git alongside the sources that
 * produced them. `npm run check:faust` asserts the two agree.
 *
 * Faust's own `dsp-meta.json` is around 6 KB per module, most of it compiler
 * options, library paths and a copy of the source. Only five fields are needed
 * at runtime, so it is trimmed to a few hundred bytes and emitted as TypeScript
 * — which means a mistyped parameter name is a compile error rather than a
 * control that silently does nothing.
 */
import { execFileSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as path from 'node:path';

const SOURCE = path.join(process.cwd(), 'src/audio/faust');
const BUILT = path.join(SOURCE, 'built');

interface FaustUiItem {
  type?: string;
  label?: string;
  index?: number;
  init?: number;
  min?: number;
  max?: number;
  step?: number;
  items?: FaustUiItem[];
}

/** What the runtime keeps about one control. See `collect`. */
interface Control {
  /** Byte offset into the DSP struct. The only field needed to *set* it. */
  at: number;
  init: number;
  min: number;
  max: number;
  step: number;
}

/**
 * Faust nests controls in groups; the leaves are what carry an index.
 *
 * **The range is kept as well as the offset, and that is the point of this
 * pass.** The first version took the byte offset alone and discarded the rest,
 * which meant every Faust control needed a hand-written slider with
 * hand-copied bounds — and `friction` shipped with seven controls and no panel
 * at all, so it was tuned by driving the compiled wasm in Node and reading
 * octave-band tables. That found real faults and it is a ridiculous way to
 * answer "is this slightly too bright".
 *
 * The `.dsp` already declares the bounds; they are the same numbers that would
 * otherwise be typed into `lil-gui` twice and drift apart once. Carrying them
 * through means any module, including ones not written yet, arrives with a
 * correct panel for free.
 *
 * `button` and `checkbox` have no declared range — Faust omits the fields — so
 * they fall back to a 0..1 step of 1, which is what they are.
 */
function collect(items: FaustUiItem[] | undefined, into: Record<string, Control>): void {
  for (const item of items ?? []) {
    if (item.items) {
      collect(item.items, into);
      continue;
    }
    if (item.label === undefined || item.index === undefined) continue;
    const min = item.min ?? 0;
    const max = item.max ?? 1;
    into[item.label] = {
      at: item.index,
      init: item.init ?? min,
      min,
      max,
      // Faust's own step is occasionally coarser than a control wants to be
      // dragged; a hundredth of the range is the floor, which for a 0..1
      // slider is 0.01 and for a 30..1400 Hz one is about 14.
      step: Math.min(item.step ?? 0.01, (max - min) / 100 || 0.01),
    };
  }
}

export function buildFaust(): { name: string; bytes: number; params: string[] }[] {
  const sources = fs
    .readdirSync(SOURCE)
    .filter((file) => file.endsWith('.dsp'))
    .sort();

  fs.mkdirSync(BUILT, { recursive: true });
  const results: { name: string; bytes: number; params: string[] }[] = [];

  for (const file of sources) {
    const name = file.replace(/\.dsp$/, '');
    const out = path.join(BUILT, name);

    // The compiler script is invoked with node directly rather than through
    // `npx`. Node 20 will not `execFile` a `.cmd` shim, so the Windows path
    // through npx needs a shell — and going via the script skips two process
    // spawns per module as well.
    execFileSync(
      process.execPath,
      [
        path.join(process.cwd(), 'node_modules/@grame/faustwasm/scripts/faust2wasm.js'),
        path.join(SOURCE, file),
        out,
        '-no-template',
      ],
      { stdio: ['ignore', 'pipe', 'pipe'] },
    );

    const wasm = fs.readFileSync(path.join(out, 'dsp-module.wasm'));
    const meta = JSON.parse(fs.readFileSync(path.join(out, 'dsp-meta.json'), 'utf8'));

    const params: Record<string, Control> = {};
    collect(meta.ui, params);

    // Flattened next to the module rather than left in its own directory: one
    // wasm and one `.ts` per model reads better in a diff than a tree of
    // identically-named files.
    fs.writeFileSync(path.join(BUILT, `${name}.wasm`), wasm);
    fs.writeFileSync(
      path.join(BUILT, `${name}.ts`),
      `// Generated by tools/faust-build.ts from ${file}. Do not edit.\n` +
        `import type { FaustMeta } from '../FaustNode';\n` +
        `import url from './${name}.wasm?url';\n\n` +
        `export const ${name}Url = url;\n\n` +
        `export const ${name}Meta = ${JSON.stringify(
          {
            name: meta.name,
            inputs: meta.inputs,
            outputs: meta.outputs,
            size: meta.size,
            params,
          },
          null,
          2,
        )} as const satisfies FaustMeta;\n\n` +
        `export type ${name[0].toUpperCase()}${name.slice(1)}Param = keyof typeof ${name}Meta.params;\n`,
    );
    fs.rmSync(out, { recursive: true, force: true });

    results.push({ name, bytes: wasm.length, params: Object.keys(params) });
  }

  return results;
}

// Only when run directly, so `check:faust` can import `buildFaust` without
// triggering a rebuild as a side effect.
//
// Matched on the entry point's *name*. Comparing `import.meta.url` against
// `process.argv[1]` is the usual idiom and it is wrong here: esbuild inlines
// this module into `faust-check.mjs`, so both sides become that same bundle
// and the guard opens for the check as well — which silently compiled every
// module twice.
if (path.basename(process.argv[1] ?? '').startsWith('faust-build')) {
  for (const result of buildFaust()) {
    console.log(
      `built  ${result.name.padEnd(14)} ${(result.bytes / 1024).toFixed(1)} kB  ` +
        `[${result.params.join(', ')}]`,
    );
  }
}
